In [ ]:
import typing

from pathlib import Path

import pandas as pd

from datasets import Dataset

In [ ]:
# dataset_name = "saiteki-kai__BeaverTails-Evaluation-it"
dataset_name = "saiteki-kai__BeaverTails-it"

metrics = [
    "google__metricx-24-hybrid-xxl-v2p6",
    "Unbabel__wmt23-cometkiwi-da-xxl",
    "Unbabel__XCOMET-XXL",
]

models = [
    "haoranxu__X-ALMA-13B-Group2",
    "Unbabel__TowerInstruct-Mistral-7B-v0.2",
    "CohereForAI__aya-23-35B",
    "facebook__nllb-200-3.3B",
    "facebook__nllb-moe-54B",
    "LLaMAX__LLaMAX3-8B-Alpaca",
]

splits = ["330k_train", "330k_test"]
# splits = ["test"]

for metric in metrics:
    df_results = pd.DataFrame()
    for model in models:
        df = pd.DataFrame()
        for split in splits:
            filepath = Path(f"../outputs/{dataset_name.split('__')[-1]}/scores/{metric}/{model}/{split}/scores.parquet")

            if not filepath.exists():
                print(filepath)
                continue

            ds = Dataset.from_parquet(str(filepath))
            ds = typing.cast(Dataset, ds)
            df_split = typing.cast(pd.DataFrame, ds.to_pandas())

            df = pd.concat([df, df_split])

        df["model"] = model
        df["model"] = pd.Categorical(df["model"], models)
        df = df.rename(columns={col: col.split("_")[0] for col in df.columns})

        df_results = pd.concat([df_results, df])

    print(metric)
    p = 100 if "metricx" not in metric else 1

    # display(df_results.groupby("model", observed=True).agg(lambda x: f"{x.mean()*p:.2f} ± {x.std()*p:.2f}"))
    display(df_results.groupby("model", observed=True).agg(lambda x: f"{x.mean() * p:.2f}"))  # noqa: B023
    print("\n")

../outputs/BeaverTails-it/scores/google__metricx-24-hybrid-xxl-v2p6/facebook__nllb-200-3.3B/330k_train/scores.parquet
../outputs/BeaverTails-it/scores/google__metricx-24-hybrid-xxl-v2p6/facebook__nllb-200-3.3B/330k_test/scores.parquet
../outputs/BeaverTails-it/scores/google__metricx-24-hybrid-xxl-v2p6/facebook__nllb-moe-54B/330k_train/scores.parquet
google__metricx-24-hybrid-xxl-v2p6

                                       prompt response
model
haoranxu__X-ALMA-13B-Group2              1.38     2.03
Unbabel__TowerInstruct-Mistral-7B-v0.2   1.38     1.86
CohereForAI__aya-23-35B                  1.59     2.14
LLaMAX__LLaMAX3-8B-Alpaca                2.16     3.43
facebook__nllb-moe-54B                   2.34     6.93

../outputs/BeaverTails-it/scores/Unbabel__wmt23-cometkiwi-da-xxl/facebook__nllb-200-3.3B/330k_train/scores.parquet
../outputs/BeaverTails-it/scores/Unbabel__wmt23-cometkiwi-da-xxl/facebook__nllb-200-3.3B/330k_test/scores.parquet
../outputs/BeaverTails-it/scores/Unbabel__wmt23-cometkiwi-da-xxl/facebook__nllb-moe-54B/330k_train/scores.parquet
Unbabel__wmt23-cometkiwi-da-xxl

                                       prompt response
model
haoranxu__X-ALMA-13B-Group2             85.51    87.58
Unbabel__TowerInstruct-Mistral-7B-v0.2  85.00    88.00
CohereForAI__aya-23-35B                 83.62    86.78
LLaMAX__LLaMAX3-8B-Alpaca               80.20    81.71
facebook__nllb-moe-54B                  79.44    64.58

../outputs/BeaverTails-it/scores/Unbabel__XCOMET-XXL/facebook__nllb-200-3.3B/330k_train/scores.parquet
../outputs/BeaverTails-it/scores/Unbabel__XCOMET-XXL/facebook__nllb-200-3.3B/330k_test/scores.parquet
../outputs/BeaverTails-it/scores/Unbabel__XCOMET-XXL/facebook__nllb-moe-54B/330k_train/scores.parquet
Unbabel__XCOMET-XXL

                                       prompt response
model
haoranxu__X-ALMA-13B-Group2             95.37    89.06
Unbabel__TowerInstruct-Mistral-7B-v0.2  95.11    89.71
CohereForAI__aya-23-35B                 94.63    88.17
LLaMAX__LLaMAX3-8B-Alpaca               93.13    83.22
facebook__nllb-moe-54B                  92.20    79.35